name: NIKE X BORED APE 

on:
  push:https://www.element.market/collections/the-bored-apes-nike-metaverse-official
    branches: [ Nervermain ]
  pull_request:
    branches: [ Nervermain ]

jobs:
  build:https://www.element.market/collections/the-bored-apes-nike-metaverse-official

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
